Update CI.Build_Test.yml
update code coverage

diff --git a/.github/workflows/CI.Build_Test.yml b/.github/workflows/CI.Build_Test.yml
--- a/.github/workflows/CI.Build_Test.yml
+++ b/.github/workflows/CI.Build_Test.yml
@@ -43,4 +43,17 @@ jobs:
         # xvfb-run -a ng test --configuration=development
         xvfb-run -a ng test --configuration=development --browsers=ChromeHeadless --watch=false --progress=true
         # timeout-minutes: 4
-  
+        
+    - name: Check code coverage
+      run: |
+        COVERAGE_THRESHOLD=80
+        coverage=$(grep -oP "(?<=statements.\s)(\d+.\d+)" ./coverage/lcov-report/index.html)
+        if (( $(echo "$coverage < $COVERAGE_THRESHOLD" | bc -l) )); then
+          echo "Code coverage is less than $COVERAGE_THRESHOLD%. Sending message..."
+          # Add your custom logic here to send a message or take any other action
+          # For example, you can use a messaging service or create a GitHub issue
+          # You can also use the GitHub API to add a comment or set the workflow status
+          exit 1  # This will mark the workflow as failed
+        else
+          echo "Code coverage is acceptable: $coverage%"
+        fi
