Update CI.Build_Test.yml

diff --git a/.github/workflows/CI.Build_Test.yml b/.github/workflows/CI.Build_Test.yml
--- a/.github/workflows/CI.Build_Test.yml
+++ b/.github/workflows/CI.Build_Test.yml
@@ -64,36 +64,37 @@ jobs:
 
         if [ "$(echo "$statement_coverage < ${{ env.CODE_COVERAGE_THRESHOLD }}" | bc)" -eq 1 ]; then
           echo "Statement Code coverage is less than ${{ env.CODE_COVERAGE_THRESHOLD }}%. JOB ABORTED !! ..."
-           exit 1  # This will mark the workflow as failed
+       
+          exit 1  # This will mark the workflow as failed
         else
-          echo "::set-output name=coverage_passed::true"
+          
           echo "Statement Code coverage is acceptable: $statement_coverage%"
         fi
 
         if [ "$(echo "$branch_coverage < ${{ env.CODE_COVERAGE_THRESHOLD }}" | bc)" -eq 1 ]; then
           echo "Branch Code coverage is less than ${{ env.CODE_COVERAGE_THRESHOLD }}%. JOB ABORTED !!..."
-          echo "::set-output name=coverage_passed::false"
+         
            exit 1  # This will mark the workflow as failed
         else
-          echo "::set-output name=coverage_passed::true"
+        
           echo "Branch Code coverage is acceptable: $branch_coverage%"
         fi
 
         if [ "$(echo "$function_coverage < ${{ env.CODE_COVERAGE_THRESHOLD }}" | bc)" -eq 1 ]; then
           echo "Function Code coverage is less than ${{ env.CODE_COVERAGE_THRESHOLD }}%.  JOB ABORTED !!..."
-          echo "::set-output name=coverage_passed::false"
+         
            exit 1  # This will mark the workflow as failed
         else
-          echo "::set-output name=coverage_passed::true"
+         
           echo "Function Code coverage is acceptable: $function_coverage%"
         fi
 
         if [ "$(echo "$line_coverage < ${{ env.CODE_COVERAGE_THRESHOLD }}" | bc)" -eq 1 ]; then
           echo "Line Code coverage is less than ${{ env.CODE_COVERAGE_THRESHOLD }}%.  JOB ABORTED !!..."
-          echo "::set-output name=coverage_passed::false"
+         
            exit 1  # This will mark the workflow as failed
         else
-          echo "::set-output name=coverage_passed::true"
+         
           echo "Line Code coverage is acceptable: $line_coverage%"
         fi
         
